# Generated by Django 4.1.13 on 2024-04-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
